version: '3.6'

services:
  web:
    image: lisotton/focoradical-php:8.1-dev
    ports:
      - "80:80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/focoradical.ini
      - ./config/php/php-dev.ini:/usr/local/etc/php/conf.d/z-development.ini
      - ./config/apache/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=frontend.localhost
      - BASIC_AUTH_ENABLED=0
      - COOKIE_VALIDATION_KEY=7fasd78ajk4qlkjaf9843kjjkf9843
      - DB_HOST=mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=inscricoes_dev
      - TZ=America/Fortaleza

  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
